version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.7.0
        container_name: elasticsearch
        hostname: elasticsearch
        restart: always
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - redcat-network
        volumes:
            - elk:/usr/share/elasticsearch/data
    kibana:
        image: kibana:7.7.0
        container_name: kibana
        hostname: kibana
        restart: always
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - redcat-network
    logstash:
        image: logstash:7.7.0
        container_name: logstash
        hostname: logstash
        restart: always
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - ./logstash:/usr/share/logstash/pipeline/
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - redcat-network
networks:
    redcat-network:
         driver: bridge
         external: true
volumes:
    elk:
        external: true