version: "3.7"
services:
  mongodb:
    container_name: aiot-mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - /docker/mongo/volume/data/db:/data/db
  mongo-express:
    container_name: aiot-mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=aiot-mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=${PASSWORD}
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - '8081:8081'